# This file was generated by GoReleaser. DO NOT EDIT.
cask "genvid" do
  version "0.0.2"

  on_macos do
    on_intel do
      sha256 "6c1dee348c569ee9c80adda10aea2fa9f9db0bb1d0c063eaf22deb6890e3ce2a"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e0114e8e4ebf841591bbd56bac21a2f728ddc908a9fddde85e7010af6bd8694a"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "28e8bd7c57ccd040193c4316162726eb8a481daf5b9aa4ebe7656984edf17508"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2786f4b53f4c423f0d0d93f277d4e26812e5c4bae49ecf2605989797e5855ef9"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "genvid"
  desc "Genvid AI Production System command-line interface"
  homepage "https://genvid.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genvid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/genvid"]
    end
  end

  # No zap stanza required

end
