# This file was generated by GoReleaser. DO NOT EDIT.
cask "genvid" do
  version "0.0.1"

  on_macos do
    on_intel do
      sha256 "d9ffad1c1b45057fd983e1ba6500d6b72e294fb9c9926c24d955b18e5d525ee7"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "07a0094025298135c113d3ce06e479923b86aef13e76501e563affdfe10bad85"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "528ef9f9f950dd477634e27d3a9a6bf45e786b70470f5de59eba681a7e93e3ea"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dc26583378d7cfb6b8a929b0d090dcec0a9c4d56f110ee4467ed3f76a7ae56a9"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_arm64.tar.gz"
    end
  end

  name "genvid"
  desc "Genvid AI Production System command-line interface"
  homepage "https://genvid.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genvid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/genvid"]
    end
  end

  # No zap stanza required

end
