# This file was generated by GoReleaser. DO NOT EDIT.
cask "genvid" do
  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "b962a492c0f2699e992772f3d93226e0d28efe2244a451e68b5e171ada862ec8"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6df855f751d63a57579848ca55d25116813b64e330e0aa4091e657ac7c9d2c83"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "727a447a3768b43d64ec88a79f2bd68e7772f163d2ad2af2ff343b09d7197518"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcf59819f57cc8762b4875ee7c1dc5768a906b7cacbaf9c0a8c5843f9f0fc94f"
      url "https://github.com/genvid-holdings/genvid-cli/releases/download/#{version}/genvid_#{version}_linux_amd64.tar.gz"
    end
  end

  name "genvid"
  desc "Genvid AI Production System command-line interface"
  homepage "https://genvid.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "genvid"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/genvid"]
    end
  end

  # No zap stanza required
end
